import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingBottom: 8,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
    },
    closeButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#f3f4f6',
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollContent: {
        paddingBottom: 16,
    },
    nameSection: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f9fafb',
        padding: 14,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: '#e8e8ec',
        marginBottom: 14,
    },
    nameIcon: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: '#1a1a2e',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    nameInfo: {
        flex: 1,
    },
    label: {
        color: '#6b7280',
        fontSize: 12,
        fontWeight: '500',
        marginBottom: 3,
    },
    nameValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
    },
    shareButton: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0.5,
        borderColor: '#e5e7eb',
    },
    rowFlex: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 14,
    },
    flex1: {
        flex: 1,
        backgroundColor: '#ffffff',
        padding: 14,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: '#e8e8ec',
    },
    detailRowIcon: {
        marginBottom: 8,
    },
    value: {
        fontSize: 14,
        color: '#111827',
        fontWeight: '600',
    },
    valueMuted: {
        fontSize: 14,
        color: '#9ca3af',
        fontStyle: 'italic',
    },
    contactSection: {
        marginBottom: 14,
    },
    contactPillsWrapper: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    contactPill: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f9fafb',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        gap: 8,
        borderWidth: 0.5,
        borderColor: '#e5e7eb',
    },
    contactValue: {
        fontSize: 13,
        color: '#374151',
        fontWeight: '500',
    },
    shareAmountSection: {
        borderTopColor: '#f0f0f0',
        borderTopWidth: 0.5,
        paddingTop: 20,
        marginBottom: 14,
        gap: 10,
    },
    shareTitle: {
        fontWeight: '600',
        fontSize: 14,
        color: '#111827',
    },
    input: {
        backgroundColor: '#ffffff',
        borderWidth: 0.5,
        borderColor: '#e5e7eb',
        borderRadius: 10,
    },
    shareButtonFull: {
        minHeight: 44,
        borderRadius: 10,
    },
    footerActions: {
        flexDirection: 'row',
        gap: 12,
        paddingTop: 8,
    },
    deleteButton: {
        flex: 1,
        backgroundColor: '#fef2f2',
        padding: 12,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 48,
    },
    deleteText: {
        color: '#ef4444',
        fontSize: 15,
        fontWeight: '600',
    },
    editButton: {
        flex: 1,
        minHeight: 48,
        borderRadius: 10,
    },
});
