import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingBottom: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#111827',
    },
    closeButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#f3f4f6',
        alignItems: 'center',
        justifyContent: 'center',
    },
    contentGroup: {
        gap: 20,
    },
    nameSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#f9fafb',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    nameInfo: {
        flex: 1,
        marginRight: 16,
    },
    label: {
        color: '#6b7280',
        fontSize: 13,
        fontWeight: '500',
        marginBottom: 4,
    },
    nameValue: {
        fontSize: 18,
        fontWeight: '600',
        color: '#111827',
    },
    shareButton: {
        backgroundColor: '#ffffff',
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#f3f4f6',
    },
    rowFlex: {
        flexDirection: 'row',
        gap: 16,
    },
    flex1: {
        flex: 1,
        backgroundColor: '#ffffff',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    value: {
        fontSize: 15,
        color: '#111827',
        fontWeight: '600',
    },
    valueMuted: {
        fontSize: 15,
        color: '#9ca3af',
        fontStyle: 'italic',
    },
    contactSection: {
        gap: 12,
    },
    contactPillsWrapper: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    contactPill: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f9fafb',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        gap: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    contactValue: {
        fontSize: 14,
        color: '#374151',
        fontWeight: '500',
    },
    shareAmountSection: {
        borderTopColor: '#f0f0f0',
        borderTopWidth: 1,
        paddingTop: 24,
        marginTop: 4,
        gap: 12,
    },
    shareTitle: {
        fontWeight: '600',
        fontSize: 15,
        color: '#111827',
    },
    input: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 10,
    },
    shareButtonFull: {
        minHeight: 48,
        borderRadius: 10,
    },
    footerActions: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 'auto',
        paddingTop: 24,
    },
    deleteButton: {
        flex: 1,
        backgroundColor: '#fef2f2',
        padding: 12,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 52,
    },
    deleteText: {
        color: '#ef4444',
        fontSize: 16,
        fontWeight: '600',
    },
    editButton: {
        flex: 1,
        minHeight: 52,
        borderRadius: 12,
    },
});
